services:
  db:
    image: mysql:8.0.42
    container_name: retofullstack-db
    environment:
      MYSQL_ROOT_PASSWORD: Pumamunoz14!
      MYSQL_DATABASE: proyectoGym
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - reto-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: retofullstack-backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/proyectoGym?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Pumamunoz14!
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - reto-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: retofullstack-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - reto-net

volumes:
  mysql-data:

networks:
  reto-net:
